services:
    tatiana5.disallowlinks.listener:
        class: tatiana5\disallowlinks\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@user'
            - '@dispatcher'
        tags:
            - { name: event.listener }
